#version: "3.8"

x-base_service: &base_service
  environment:
    - IP_ADDRESS=192.168.55.1
    - PORT=11311
    - DISPLAY=${DISPLAY}
    - ROS_MASTER_URI=http://10.0.0.99:11311
    - ROS_IP=10.0.0.99
  volumes:
    - .:/run/detect
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /dev/video0:/dev/video0
    - /dev:/dev
  network_mode: host

x-with-gpu: &with_gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [ gpu ]

services:
  roscore:
    <<: *base_service
    image: arm64v8/ros:noetic-ros-core
#    image: osrf/ros:noetic-desktop-full
    profiles: [ "core" ]
    command: [ "roscore", "-v" ]
#    command: [ "sh", "-c", "ROS_MASTER_URI=http://192.168.55.1:11311/ ROS_IP=192.168.55.1 roscore -v" ]

  bridge:
    <<: *base_service
    build:
      context: .
      dockerfile: ./bridge.Dockerfile
    profiles: [ "bridge" ]
    command: [ "rosrun", "foxglove_bridge", "foxglove_bridge" ]

  img_detect: &img_detect
    <<: *base_service
    build:
      context: .
      dockerfile: ./detect/v2.Dockerfile
    profiles: [ "cpu" ]
    command: [
      "python3", "/run/detect/detect/detect_image.py",
      "-m", "/run/detect/best_1.pt",
      "-c", "0.6",
      "-i", "camera/raw"
    ]

  img_detect_gpu:
    <<: [ *img_detect, *with_gpu ]
    profiles: [ "gpu" ]

  img_pub:
    <<: *base_service
    build:
      context: .
      dockerfile: ./camera/Dockerfile
    profiles: [ "webcam" ]
    privileged: true
#    command: [ "python3", "/run/detect/camera/img_pub.py", "-f", "/run/detect/videos/UW vs UCSD Group A BO2  _ 2022 RoboMaster University League North America.mp4" ]
    command: [ "python3", "/run/detect/camera/img_pub.py", "-f", "0" ]
    depends_on:
      - roscore
